### ISSUE TITLE
Mismatch between name retrieved with SSO and from author list

### ISSUE THREAD

**Issue by gdujany** [gdujany/Condorcet#23]
The name I get from the SSO is often different from the one I registered in the author list mainly because:
- Multiple name or surnames (eg. Tim Head)
- Spelling mistakes (eg. Helena Graverini)
- Russian names (eg. Filippov -> Philippov)

**Comment by gdujany** [comment]
To mitigate it I experimented with [fuzzywuzzy](https://github.com/seatgeek/fuzzywuzzy) to have more permissive matching, see pull request #24

**Comment by gdujany** [comment]
#25 is an alternative approach

**Comment by gdujany** [comment]
Another way to pass the buck could be to ask the creation of an egroup with all the voters in it. As long as I don't have to fill that egroup myself it would be a quick solution because checking the egroup appurtenance is super easy with the SSO.

**Comment by apuignav** [comment]
I agree. I think this should be up to the Collaboratin Board/membership
comittee/however handles this thing. I think this shouldn't be up to us in
the sense that if there isn't a good solution and has to be done manually,
it's the job of the people who know....

Albert

On Sun, May 3, 2015 at 7:47 PM, Giulio Dujany notifications@github.com
wrote:

> Another way to pass the buck could be to ask the creation of an egroup
> with all the voters in it. As long as I don't have to fill that egroup
> myself it would be a quick solution because checking the egroup
> appurtenance is super easy with the SSO.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/issues/23#issuecomment-98514180.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
On Mon, May 4, 2015 at 8:44 AM Albert Puig notifications@github.com wrote:

> I agree. I think this should be up to the Collaboratin Board/membership
> comittee/however handles this thing. I think this shouldn't be up to us in
> the sense that if there isn't a good solution and has to be done manually,
> it's the job of the people who know....
> 
> The problem will be that others won't want to do it if it involves manual
> labour ...

How much could we automate this? Require people to "register to vote" like
in a real election? As part of this they go to a webpage which says "we
think you are eligible to vote" if there is a clear match or "We do not
think you are eligible to vote but there are people very similar to you who
are: list of names" please pick one. Then all we/CB have to do is approve
those choices.
