### ISSUE TITLE
Tara can't vote

### ISSUE THREAD

**Issue by betatim** [gdujany/Condorcet#30]
Hi - I should be eligible to vote, but when i try

https://lhcb-condorcet.web.cern.ch/lhcb-condorcet/testElection/

I get the message that i'm ineligible...

Best wishes, Tara Shears

Her email address is: Tara.Shears@cern.ch

**Comment by apuignav** [comment]
CERN ID is properly matched.

**Comment by gdujany** [comment]
Solved, it was an authentication problem, removing z5 requirements fixed it
