### ISSUE TITLE
Jessica Prisciandaro can't vote

### ISSUE THREAD

**Issue by betatim** [gdujany/Condorcet#33]
Jessica.Prisciandaro@cern.ch

SHe gets an error from the voting system telling her that her name doesn't appear in the list

**Comment by apuignav** [comment]
She's not in the csv file.

**Comment by betatim** [comment]
She is only in the 2015 author list, not the 2016 one.

**Comment by apuignav** [comment]
Yes, this is apparently a mistake from the secretaries. She went to ask, so
we should clarify with them.

On Tue, May 12, 2015 at 3:20 PM, Tim Head notifications@github.com wrote:

> She is only in the 2015 author list, not the 2016 one.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/issues/33#issuecomment-101272351.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by gdujany** [comment]
If she appears in the 2015 and she is still in LHCb (which I think it is proved by the fact she tried to vote) I think we should add her without waiting the confirmation. The 2016 trick works assuming that at the secretariat put as an end date some date far in the future that is then set to now when people actually leave.

**Comment by betatim** [comment]
:email: sent
