### ISSUE TITLE
Janine Mueller can't vote

### ISSUE THREAD

**Issue by betatim** [gdujany/Condorcet#35]
There is an umlaut in her surname.

DIdn't give a cern email address

**Comment by apuignav** [comment]
There is no Janine in the CSV file, didn't even try the umlaut.

**Comment by betatim** [comment]
She appears in both authorlists

**Comment by gdujany** [comment]
Sorry, my fault, to simplify things as I had only initials and surnames in the tex file I took just one person per surname planning to check for multiples surnames on a later stage which never happened.

**Comment by apuignav** [comment]
Ah! That explains the Mueller mystery :-) Good it's solved.

On Tue, May 12, 2015 at 6:27 PM, Giulio Dujany notifications@github.com
wrote:

> Sorry, my fault, to simplify things as I had only initials and surnames in
> the tex file I took just one person per surname planning to check for
> multiples surnames on a later stage which never happened.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/issues/35#issuecomment-101339520.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
This is fixed in commit c3ffb0d

**Comment by betatim** [comment]
In principle this issue should close itself when we merge #39

**Comment by apuignav** [comment]
True, sorry, I was too fast.

**Comment by betatim** [comment]
:email: sent
