### ISSUE TITLE
Vanessa Mueller can't vote

### ISSUE THREAD

**Issue by betatim** [gdujany/Condorcet#37]
Vanessa Müller

vanessa.mueller@cern.ch

**Comment by apuignav** [comment]
Missing from CSV.

**Comment by apuignav** [comment]
Missing from the CSV file.

**Comment by betatim** [comment]
748603

should we just add her? How do I know if she is meant to be eligible?

**Comment by apuignav** [comment]
We should check in the author DB. Maybe the names with umlauts got lost in
Giulio's translation.

On Tue, May 12, 2015 at 3:05 PM, Tim Head notifications@github.com wrote:

> 748603
> 
> should we just add her? How do I know if she is meant to be eligible?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/issues/37#issuecomment-101268196.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
```
$ grep Vanessa Authors1May201*tex
```

so she isn't eligible

**Comment by betatim** [comment]
She is in both autorlists

**Comment by apuignav** [comment]
You tell her :-)

On Tue, May 12, 2015 at 3:11 PM, Tim Head notifications@github.com wrote:

> $ grep Vanessa Authors1May201*tex
> 
> so she isn't eligible
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/issues/37#issuecomment-101270048.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by betatim** [comment]
:email: sent
