### ISSUE TITLE
Send secret key by email

### ISSUE THREAD

**Issue by betatim** [gdujany/Condorcet#43]
I would like to suggest a small feature that could be quite useful. Since you have access to our CERN account information (we are identified via SSO), why not emailing us our secret key after the vote is cast?
I may be wrong, but I have the impression that a non-negligible percentage of us will forget or neglect to write down his/her secret key, especially if the election will last for a full day or more (browser tabs will be closed when leaving the office).

**Comment by apuignav** [comment]
Since we discussed this and it was not obvious how to do it properly, maybe we could add a "print" button in the secret key page.
