### ISSUE TITLE
Franz Muheim cannot vote

### ISSUE THREAD

**Issue by apuignav** [gdujany/Condorcet#51]
He is not authorized. I asked him to try his other username `fmuheim`

```
muheim   xv  PA 15259 1158 03/05/15 00:45 /bin/tcsh /afs/cern.ch/user/m/muheim
muheimo  def-cg SA  1903 2766 13/05/14 00:55 /bin/tcsh /afs/cern.ch/user/m/muheimo
fmuheim  z5  SA 28962 1470 18/03/15 14:24 /bin/csh  /afs/cern.ch/user/f/fmuheim
```

**Comment by apuignav** [comment]
He's not happy:

```
I have never used such an account  on the web,
in fact I didn't know it existed outside lxplus.
and I wouldn't know my password.

As I told Bernhard,
voting has to work without us
having to resurrect accounts 
which we didn't know we have.
```

I don't know how we can solve this, though, his other accounts are not in z5:

```
muheim   xv  PA 15259 1158 03/05/15 00:45 /bin/tcsh /afs/cern.ch/user/m/muheim
muheimo  def-cg SA  1903 2766 13/05/14 00:55 /bin/tcsh /afs/cern.ch/user/m/muheimo
fmuheim  z5  SA 28962 1470 18/03/15 14:24 /bin/csh  /afs/cern.ch/user/f/fmuheim
```

**Comment by betatim** [comment]
How can he access things on indico etc that are protected by the same SSO? Shouldn't they also reject him with a 401?

If we can figure this out we might be able to make it work.

**Comment by apuignav** [comment]
I think the problem is that our website is protected by the z5 group permissions. I seem to remember there was a reason for that, but now I can't recall it.

**Comment by gdujany** [comment]
I guess we can remove the need that the account is in the z5 group from the .htaccess removing the last line. We naively expected this to be redundant and not cause problem but it seems not true.I asked Joel to do a test, if he succeeds I guess we can proceed.

```
 Il Martedì 12 Maggio 2015 18:51, Albert Puig <notifications@github.com> ha scritto:
```

 He's not happy:I have never used such an account  on the web,
in fact I didn't know it existed outside lxplus.
and I wouldn't know my password.

As I told Bernhard,
voting has to work without us
having to resurrect accounts 
which we didn't know we have.
I don't know how we can solve this, though, his other accounts are not in z5:muheim   xv  PA 15259 1158 03/05/15 00:45 /bin/tcsh /afs/cern.ch/user/m/muheim
muheimo  def-cg SA  1903 2766 13/05/14 00:55 /bin/tcsh /afs/cern.ch/user/m/muheimo
fmuheim  z5  SA 28962 1470 18/03/15 14:24 /bin/csh  /afs/cern.ch/user/f/fmuheim

**Comment by gdujany** [comment]
a priori now it should be solved by 95448b0d7bb901832b09f06727f1b7235d15ed4c
like all the other unauthorized issues

**Comment by betatim** [comment]
For me this references a commit commenting out the help link :-(

**Comment by gdujany** [comment]
Sorry, this should be the correct one b00e150ccf9486a767d1622f5fc3f693af4b867a

**Comment by betatim** [comment]
Did someone contact him already to try again since the z5 requirement was dropped? I can do it, but it would be "nicer" if the person who he has been emailing (@apuignav?) with does it.

**Comment by apuignav** [comment]
:email: sent

**Comment by apuignav** [comment]
He voted and everything went well.
