### ISSUE TITLE
Make more clear that cadidates are ranked from top to bottom

### ISSUE THREAD

**Issue by gdujany** [gdujany/Condorcet#58]

**Comment by betatim** [comment]
This is not addressed by #41 ?

**Comment by gdujany** [comment]
A priori yes but, maybe I am doing something silly,  can't see this change in the head of the master

**Comment by betatim** [comment]
Any ideas @apuignav?

**Comment by alexpearce** [comment]
Looks like #41 was closed rather than merged.

**Comment by alexpearce** [comment]
I reopened and merged it.
