### ISSUE TITLE
Check that no error is caused by candidates' names too long

### ISSUE THREAD

**Issue by gdujany** [gdujany/Condorcet#59]
Until now we tested wit relatively short name, we should check that nowhere we assume a too low limit on the length of the candidate's name. 
From the python's side we shuold be safe, from the js and html I don't know

**Comment by apuignav** [comment]
I'll test this asap, indeed in the css there is a width assigned to the columns,and if a name is wider it may look weird. This cn be adjusted, but I would not want to do it dynamically.

Let me see the longest name we can get in there that still looks good and I'll get back to you.
