### ISSUE TITLE
Create admin interface

### ISSUE THREAD

**Issue by apuignav** [gdujany/Condorcet#6]
An "admin" interface should be added.

My first thoughts on the topic are:
- It should be only accessible to certain user names (the "admins") defined in a DB or from the admin interface itself.
- It should provide simple access to:
  - Election configuration (add, remove candidates, reset, set voting dates, etc).
  - Election scrutiny.
  - Making election results public.

We could use this issue to define the specs of this admin area before implementing it.

**Comment by gdujany** [comment]
I started implementing a draft of the admin page in the branch "admin". The main features you cite should be there (in a maybe simplistic way), a bit of testing is still required and the layout of the page can be improved a lot.

It would be nice if the admin page would also allow to download the authors_list used and upload a new one.

To sum up:
- Election configuration (add, remove candidates, reset, set voting dates, etc)
  -> Should be there
- Election scrutiny
  -> Admins can see the result page after the election closes even before the date when results become public
- Making election results public
  -> Admins can see the result page after the election closes and can then change the date to when the results become public

**Comment by apuignav** [comment]
I think that is about right, how can we divide the work so I can also help you with this?

**Comment by gdujany** [comment]
I would happily leave the improvement of the layout. 

For the rest I tried to be organized and  put the admins functions in updateConfig.py
I tried to be  back-compatible and starting reading the default configs from config.py 
However to have configs which can change dynamically I put them in a database
If you have time and will you could look at what I have done and give feedback about the philosophy of the implementation.

Then if you would like to change the general structure feel free otherwise I hope to have implemented it in easily extendible way and adding the other features should not be too long.

I was planning to leave it a bit a side for now so if in the next day you want to give it a look, modify and extend feel free.

**Comment by apuignav** [comment]
Perfect. I'm busy also until mid next-week, so I'll have a look then.

On Fri, Apr 10, 2015 at 1:28 AM, Giulio Dujany notifications@github.com
wrote:

> I would happily leave the improvement of the layout.
> 
> For the rest I tried to be organized and put the admins functions in
> updateConfig.py
> I tried to be back-compatible and starting reading the default configs
> from config.py
> However to have configs which can change dynamically I put them in a
> database
> If you have time and will you could look at what I have done and give
> feedback about the philosophy of the implementation.
> 
> Then if you would like to change the general structure feel free otherwise
> I hope to have implemented it in easily extendible way and adding the other
> features should not be too long.
> 
> I was planning to leave it a bit a side for now so if in the next day you
> want to give it a look, modify and extend feel free.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gdujany/Condorcet/issues/6#issuecomment-91380538.

## 

Dr. Albert Puig Navarro
Laboratoire de Physique des Hautes Energies
Ecole Polytechnique Fédérale de Lausanne (EPFL)
BSP 614.4 (Cubotron UNIL) CH-1015 Lausanne
EPFL Phone: 021 6939808
CERN Phone: 72518

**Comment by alexpearce** [comment]
Now that #15 is merged in to `master`, you could [rebase](http://git-scm.com/book/en/v2/Git-Branching-Rebasing) your `admin` branch so that the latest tests are run against it.
