### ISSUE TITLE
Move this repo to the lhcb organization?

### ISSUE THREAD

**Issue by apuignav** [gdujany/Condorcet#70]
Should we move to the lhcb organization so it's not tied to any of us?

**Comment by betatim** [comment]
:+1:

**Comment by alexpearce** [comment]
[Organisation here](https://github.com/lhcb) and [migration instructions here](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization).

**Comment by betatim** [comment]
I create a condorcet team in the orga with the four contributors to this repo as members.

**Comment by gdujany** [comment]
"You don't have admin rights to lhcb"
I guess I need admin rights before I can transfer this repo

**Comment by betatim** [comment]
Done, with great power comes great responsibility :smile:

**Comment by gdujany** [comment]
Looks like it's done, it will look nicer and more official on Albert's slides on Tuesday
